###############################################################################
# Arrmematey Installer Module
# Downloads and installs Arrmematey media automation stack
#
# Version: 1.0.0
###############################################################################

set -euo pipefail

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

print_info() {
    echo -e "${CYAN}ℹ${NC} $1"
}

print_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

error_exit() {
    print_error "$1"
    exit 1
}

# Check if directory is a git repository
is_git_repo() {
    git rev-parse &> /dev/null
}

# Download Arrmematey from GitHub
download_arrmematey() {
    local install_dir="/opt/arrmematey"
    local repo_url="https://github.com/edellingham/arrmematey.git"

    print_step "Downloading Arrmematey from GitHub..."

    # Check if already exists
    if [[ -d "$install_dir" ]]; then
        print_warning "Arrmematey directory already exists at $install_dir"
        if [[ "$INSTALL_MODE" == "interactive" ]]; then
            read -p "Remove and re-download? (y/N): " -n 1 -r
            echo ""
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                print_info "Removing existing installation..."
                rm -rf "$install_dir"
            else
                print_info "Using existing installation"
                return 0
            fi
        else
            print_info "Automated mode: Updating existing installation"
            cd "$install_dir"
            git pull
            return 0
        fi
    fi

    # Clone repository
    print_info "Cloning repository to $install_dir..."
    if git clone "$repo_url" "$install_dir"; then
        print_success "Arrmematey downloaded successfully"
    else
        error_exit "Failed to download Arrmematey"
    fi

    cd "$install_dir"
}

# Create necessary directories
create_directories() {
    print_step "Creating necessary directories..."

    local home_dir
    home_dir=$(eval echo ~)

    local directories=(
        "$home_dir/Config"
        "$home_dir/Media"
        "$home_dir/Movies"
        "$home_dir/TV"
        "$home_dir/Music"
        "$home_dir/Downloads"
    )

    for dir in "${directories[@]}"; do
        if [[ ! -d "$dir" ]]; then
            mkdir -p "$dir"
            print_success "Created: $dir"
        else
            print_info "Already exists: $dir"
        fi
    done
}

# Setup environment configuration
setup_environment() {
    print_step "Setting up environment configuration..."

    local home_dir
    home_dir=$(eval echo ~)

    local env_file="$home_dir/.env"
    local env_example="/opt/arrmematey/.env.example"

    if [[ -f "$env_file" ]]; then
        print_warning "Environment file already exists"
        if [[ "$INSTALL_MODE" == "interactive" ]]; then
            read -p "Backup and recreate? (y/N): " -n 1 -r
            echo ""
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                cp "$env_file" "${env_file}.backup.$(date +%Y%m%d-%H%M%S)"
                create_env_file "$env_example" "$env_file"
            fi
        fi
    else
        create_env_file "$env_example" "$env_file"
    fi

    # Load environment variables
    set -a
    source "$env_file"
    set +a

    print_success "Environment configuration ready"
}

# Create .env file from template
create_env_file() {
    local source_file=$1
    local dest_file=$2

    print_info "Creating environment configuration..."

    # Get current user info
    local current_user
    current_user=$(whoami)
    local current_uid
    current_uid=$(id -u)
    local current_gid
    current_gid=$(id -g)

    # Create .env with defaults
    cat > "$dest_file" <<EOF
# Arrmematey Configuration
# Generated by Arrmematey Proxmox Installer

# User Configuration
PUID=$current_uid
PGID=$current_gid
TZ=UTC

# Mullvad VPN Configuration
MULLVAD_ACCOUNT_ID=YOUR_MULLVAD_ACCOUNT_ID_HERE
MULLVAD_COUNTRY=us
MULLVAD_CITY=ny

# Port Configuration
MANAGEMENT_UI_PORT=8080
PROWLARR_PORT=9696
SONARR_PORT=8989
RADARR_PORT=7878
LIDARR_PORT=8686
SABNZBD_PORT=8080
QBITTORRENT_PORT=8081
JELLYSEERR_PORT=5055

# Directory Configuration
CONFIG_PATH=/root/Config
MEDIA_PATH=/root/Media
DOWNLOADS_PATH=/root/Downloads

# Media Paths
MOVIES_PATH=/root/Media/Movies
TV_PATH=/root/Media/TV
MUSIC_PATH=/root/Media/Music

# Download Paths
USENET_PATH=/root/Downloads/usenet
TORRENTS_PATH=/root/Downloads/torrents

# Service Passwords (change these!)
SABNZBD_PASSWORD=arrmematey_secure
JELLYSEERR_PASSWORD=arrmematey_secure

# Optional: Fanart.tv API Key (for movie backdrops)
FANART_API_KEY=

# Optional: Cloudflare Tunnel
CLOUDFLARE_TOKEN=
EOF

    print_success "Environment file created: $dest_file"
    print_warning "Please update MULLVAD_ACCOUNT_ID with your account ID"
}

# Build UI Docker image
build_ui_image() {
    print_step "Building management UI Docker image..."

    cd /opt/arrmematey/ui

    # Install UI dependencies
    print_info "Installing Node.js dependencies..."
    if npm install; then
        print_success "Dependencies installed"
    else
        error_exit "Failed to install Node.js dependencies"
    fi

    # Build Docker image
    print_info "Building Docker image..."
    if docker build -t arrstack-ui .; then
        print_success "UI Docker image built"
    else
        error_exit "Failed to build UI Docker image"
    fi

    cd /opt/arrmematey
}

# Start Arrmematey stack
start_arrmematey() {
    print_step "Starting Arrmematey stack..."

    cd /opt/arrmematey

    # Pull latest images
    print_info "Pulling Docker images..."
    if docker-compose pull; then
        print_success "Docker images pulled"
    else
        print_warning "Some images failed to pull - will try to continue"
    fi

    # Start stack
    print_info "Starting Arrmematey stack..."
    if docker-compose --profile full up -d; then
        print_success "Arrmematey stack started"
    else
        error_exit "Failed to start Arrmematey stack"
    fi

    # Wait for services to be ready
    print_info "Waiting for services to start..."
    sleep 10

    # Check service status
    print_step "Checking service status..."
    docker-compose ps

    print_success "Arrmematey stack is running!"
}

# Verify installation
verify_installation() {
    print_step "Verifying Arrmematey installation..."

    local home_dir
    home_dir=$(eval echo ~)

    local checks=(
        "/opt/arrmematey:Arrmematey directory"
        "$home_dir/.env:Environment configuration"
        "$home_dir/Config:Configuration directory"
        "$home_dir/Media:Media directory"
        "$home_dir/Downloads:Downloads directory"
    )

    local failed=0

    for check in "${checks[@]}"; do
        local path="${check%%:*}"
        local name="${check##*:}"

        if [[ -e "$path" ]]; then
            print_success "$name exists"
        else
            print_error "$name missing: $path"
            failed=1
        fi
    done

    # Check Docker containers
    print_info "Checking Docker containers..."
    if docker ps | grep -q "arrmematey\|sonarr\|radarr\|prowlarr"; then
        print_success "Arrmematey containers are running"
    else
        print_warning "No Arrmematey containers found running"
        failed=1
    fi

    if [[ $failed -eq 0 ]]; then
        print_success "Installation verified successfully!"
        return 0
    else
        print_warning "Some checks failed - manual verification may be needed"
        return 1
    fi
}

# Main function
install_arrmematey() {
    print_step "Starting Arrmematey installation..."

    # Check Docker is running
    if ! systemctl is-active --quiet docker; then
        error_exit "Docker is not running"
    fi

    # Download Arrmematey
    download_arrmematey

    # Create directories
    create_directories

    # Setup environment
    setup_environment

    # Build UI
    build_ui_image

    # Start stack
    start_arrmematey

    # Verify
    verify_installation

    echo ""
    print_success "Arrmematey installation complete!"
    echo ""
    print_info "Next step: Configure Arrmematey with your settings"
    echo ""

    return 0
}
